### ISSUE TITLE
Some Help Requested

### ISSUE THREAD

**Issue by 344Clinton** [Kalidomra/ADE-Commander#1]
LOVE my ADE!

Can you expand on the CTRL+F function? The help states "...Control-F : Format Image
Format the currently highlighted image. It will only erase the image. This is meant to replace the factory format command if it is disabled in the ADE configuration. In order to format for EOS or CP/M use you will need to use an alternate program..."

I wanted a new ddp. I selected CTRL+N and made the new image. However, it is inoperative in smartwriter. I then tried to CTRL+F to no avail...This was all before I read the documentation of course!!!!

What program would I use to format it for EOS or CP/M?
If I have a working smartwriter dsk/ddp image and copy it, would formatting (with CTRL+F) still let me use it in smartwriter?

**Comment by JohnLundy** [comment]
I will give you my best answer.

CTRL+F wipes the image with all E5’s and there is no real actual formatting and more like making a virgin disk format that can be properly formatted later with native ADAM formatting software, either it be EOS or CP/M. I can see using the name format might seem confusing. I personally use the various blank media images found at colecoadam.net and adamarchive.org instead. This is especially true for DDP images and the only way.

A great program to format disk (.dsk) images is to use Coleco’s Disk Manager, Walters Formatter III, or Filemanager v.3, which are also available on those websites. DDP images can not be formatted and you will need to download one of the DDP images available. Filemanager can zero them out clean, but does not actually format them. That was never possible on the ADAM. You will need to reference the CP/M manual for proper formatting. I'm not a CP/M user.

The blank DDP and disk images available will work fine in SmartWRITER.

I like to keep one of every type of blank media in a blank media folder on each SD card. I simply copy (CTRL+C) and paste (CTRL+V) where I want to have a new blank image located, followed by renaming (CTRL-R) to what I wan it to be named.

**Comment by Kalidomra** [comment]
Great response John. Thanks for the info.

**Comment by 344Clinton** [comment]
Great stuff! Thanks. Clears it up!
